export enum EventsMap {
  login = "Login success",
  logout = "Logout success",
  loginOut = "Logout button clicked",
  aboutOpen = "Open about page",
  initial = "Load initial page",
  submitLogin = "Submit login form",
  getActiveUsers = "Get active users from server",
  getInactiveUsers = "Get inactive users from server",
  contactsUpdated = "Update contacts collection",
  externalLogin = "External login",
  externalLogout = "External logout",
  getHistory = "Server response with messages history",
  error = "Server response with error",
  loginError = "Server response with login error",
  contactClicked = "User clicked on contact",
  sendMessageCkick = "User sent message",
  messageSent = "Server response on message sent",
  messageDelivered = "Server response on message delivery status change",
  messageRead = "Server response on message read status change",
  messageEdit = "Server response on message edit status change",
  markMessagesAsRead = "Set messages as read",
  scrollMessagesContainer = "User scroll message container",
  messageContainerClicked = "User clicked on message container",
  removeMessageClicked = "User clicked on remove message button",
  editMessageClicked = "User clicked on edit message button",
  applyEditMessage = "User clicked on apply edit",
  messageDelete = "Server response on message delete status change",
  contactsFilter = "User type in the contacts filter field",
  reconnected = "Reconnection attempt",
  closeConnection = "Connection is suddenly closed",
  backRoomClicked = "Back button clicked in the chat room",
  roomOpened = "Chat room with user is opened",
  emojiSelected = "Emoji selected",
}

export type HandlerType<T extends unknown[]> = (...params: T) => void;
