#!/usr/bin/env sh
message="$(cat $1)"
commitPattern="^(feat|fix|refactor|chore|docs): .*$"
if ! [[ $message =~ $commitPattern ]];
then
  echo "Invalid commit message"
  echo "-------------------------"
  echo "Your commit message was:"
  echo $message
  echo "-------------------------"
  exit 1
fi